name: vascom
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  animated_splash_screen: ^1.3.0
  control_style: ^0.0.3
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  get: ^4.6.6
  intl: ^0.18.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-ExtraBold.otf
        - asset: assets/fonts/gilroy/Gilroy-Light.otf
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/proxima_nova/ProximaNova.otf
